import { globalStyle } from "@vanilla-extract/css";
import { vars } from "@spirit-ui/design-system/theme";

/**
 * Code block styles for code figures generated from
 * the rehypePrettyCode plugin. This will apply styles
 * for all code blocks defined in the markdown files.
 */
globalStyle("[data-rehype-pretty-code-figure]", {
  marginBlock: vars.spacing.x6,
  position: "relative",
});

globalStyle("[data-rehype-pretty-code-figure] pre", {
  background: vars.colors.neutral0,
  borderColor: vars.colors.neutral200,
  borderStyle: vars.borderStyles.solid,
  borderWidth: vars.borderWidths.small,
  paddingBlock: vars.spacing.x4,
  paddingInline: 0,
});

globalStyle("[data-rehype-pretty-code-figure] code", {
  backgroundColor: "transparent",
  borderRadius: vars.radii.none,
  padding: 0,
});

globalStyle("[data-rehype-pretty-code-figure] [data-line]", {
  alignItems: "center",
  borderLeftColor: "transparent",
  borderLeftStyle: vars.borderStyles.solid,
  borderLeftWidth: "4px",
  display: "flex",
  minHeight: "1rem",
  paddingBlock: vars.spacing.x1,
  paddingInline: vars.spacing.x2,
});

globalStyle("[data-rehype-pretty-code-figure] [data-line-numbers]", {
  counterReset: "line",
});

globalStyle("[data-line-numbers] [data-line]::before", {
  counterIncrement: "line",
  color: vars.colors.neutral900,
  content: "counter(line)",
  marginRight: vars.spacing.x4,
  textAlign: "right",
  width: "20px",
});

globalStyle("[data-rehype-pretty-code-figure] [data-highlighted-line]", {
  background: vars.colors.neutral100,
  borderLeftColor: vars.colors.neutral300,
});

globalStyle("[data-rehype-pretty-code-title]", {
  color: vars.colors.neutral900,
  fontSize: vars.fontSizes.small,
  fontWeight: vars.fontWeights.semibold,
  padding: vars.spacing.x2,
});

/**
 * ComponentPreview code block styles. These styles will apply
 * to the code blocks generated by rehype for the ComponentPreview.
 */
globalStyle("[data-component-preview-code]", {});

globalStyle("[data-component-preview-code] pre", {
  backgroundColor: vars.colors.neutral0,
  paddingBlock: vars.spacing.x4,
  paddingInline: "0px",
});

globalStyle("[data-component-preview-code] code", {
  backgroundColor: "transparent",
  borderRadius: vars.radii.none,
  padding: "0px",
});

globalStyle("[data-component-preview-code] [data-line]", {
  alignItems: "center",
  borderLeftColor: "transparent",
  borderLeftStyle: vars.borderStyles.solid,
  borderLeftWidth: "4px",
  display: "flex",
  minHeight: "1rem",
  paddingBlock: vars.spacing.x1,
  paddingInline: vars.spacing.x2,
});

globalStyle("[data-component-preview-code] [data-line-numbers]", {
  counterReset: "line",
});

globalStyle(
  "[data-component-preview-code] [data-line-numbers] [data-line]::before",
  {
    counterIncrement: "line",
    color: vars.colors.neutral900,
    content: "counter(line)",
    marginRight: vars.spacing.x4,
    textAlign: "right",
    width: "20px",
  }
);
